### PR TITLE
Fix broken quantiles (#88)

### LINKED ISSUE #88: Quantile.0.25(R) always equals Quantile.0.75(R)
```
library(EpiEstim)
data(Flu2009)
T <- nrow(Flu2009$incidence)
t_start <- seq(2, T-6) # starting at 2 as conditional on the past observations
t_end <- t_start + 6 # adding 6 to get 7-day windows as bounds included in window
res_weekly <- EpiEstim::estimate_R(Flu2009$incidence, 
                         method="parametric_si",
                         config = EpiEstim::make_config(list(
                             t_start = t_start,
                             t_end = t_end,
                             mean_si = 2.6, 
                             std_si = 1.5)))
res_weekly$R
```
results in :
```
t_start t_end   Mean(R)     Std(R) Quantile.0.025(R) Quantile.0.05(R) Quantile.0.25(R) Median(R) Quantile.0.75(R)
1        2     8 1.7357977 0.40913143        1.02874370       1.12193325        2.4589724 1.7037612        2.4589724
2        3     9 1.7491678 0.36472669        1.10882231       1.19547993        2.3891206 1.7238839        2.3891206
```
Other quantiles look OK

### PR DESCRIPTION
**Pull request by jstockwin**
Closes #88

### CODE REVIEW

**Comment by jstockwin** [comment]
@zkamvar Would you mind taking a look at this when you get the chance?

**Comment by zkamvar** [comment]
This looks good to me. There really is nothing we can do about the incidence problem until ggplot2 gets fixed.

**Comment by jstockwin** [comment]
Thanks. @zkamvar. Do you think we should wait for the issue to be resolved, or just merge with failing tests?

Currently I think I can't merge due to requested changes ("Merging can be performed automatically once the requested changes are addressed."), and probably it will say the same for failing tests...

**Comment by zkamvar** [comment]
> Thanks. @zkamvar. Do you think we should wait for the issue to be resolved, or just merge with failing tests?
> 
> ~Currently I think I can't merge due to requested changes ("Merging can be performed automatically once the requested changes are addressed."), and probably it will say the same for failing tests...~ Edit: Github was being weird, it now says approved, but I can't merge due to failing tests.

I think now that there is a new version of incidence on CRAN, the issue should be resolved. I believe the solution is to open R in the project and use `vdiffr::manage_cases()` and just make sure that they look generally okay (again, the bars will be shifted to the left a bit because of the nasty hack we had to do to get things to work properly [although I supposed the original solution itself was a nasty hack, so we are negating the nasty]).

**Comment by jstockwin** [comment]
@zkamvar I've updated the figures using `vdiffr::manage_cases()`. The bars appear in the same place, but the x-axis markers have moved to the right (which I guess is the same as the bars moving to the left and the whole thing then being moved right).

Hopefully the tests pass now...

**Comment by jstockwin** [comment]
@zkamvar Tests passed ([here](https://travis-ci.org/github/annecori/EpiEstim/builds/668645200)), but on my screen at least github is still saying "Waiting for status to be reported". Not sure if it's a Travis problem or a GitHub problem... hopefully it sorts itself out :/

**Comment by jstockwin** [comment]
@zkamvar I have restarted the travis build, since something clearly went wrong. I can now see that GitHub knows it's running, so this time everything should actually go green. Not sure what happened there...

Are you happy to merge once green? Do you know how to get an updated version on CRAN?

**Comment by jstockwin** [comment]
Also I've just pushed a new commit before I forgot to update `NEWS.md`...

**Comment by zkamvar** [comment]
LGTM! Thank you ^_^

**Pull request merged**
