### PR TITLE
Fix 35

### PR DESCRIPTION
**Pull request by annecori**

### CODE REVIEW

**Comment by zkamvar** [comment]
> I don't think this is a terribly necessary change since you've already fixed the issue in [1682582](https://github.com/annecori/EpiEstim/commit/1682582323ea0e3c5473d777e1b28b443362afd7). I think these changes just end up complicating things more and would suggest to close this PR.

I think the reason why the above commit did not actually close the issue is because you wrote "Fixes issue #35" as opposed to "Fixes #35", which is all weird github semantics :man_shrugging:

**Comment by annecori** [comment]
so I think a while ago I did fix these but I recently introduced some new code with 1:T type things. so just wanted to make sure I got rid of these newly appeared issues

**Comment by zkamvar** [comment]
> so I think a while ago I did fix these but I recently introduced some new code with 1:T type things. so just wanted to make sure I got rid of these newly appeared issues

From what I can see, these won't be a problem because the only real 1:T type thing is the 1:nrow(x), but it's in an example and part of a data set that we control, so it's not really an issue. 

I still recommend closing it.

**Comment by annecori** [comment]
ok cool so not merging the PR and closing the issue or merging the PR and closing the issue?

**Comment by zkamvar** [comment]
definitely **not** merging and closing (which i will do)

**Pull request closed without merging**
